name: build_jekyll
description: custom build jekyll
inputs:
  build_source:
    description: source directory for build
    required: true 
    type: string
  build_destination:
    description: destination directory for build
    required: true 
    type: string
runs:
  using: "composite"
  steps:
    - name: build jekyll
      shell: bash
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build \
        --source ./${{inputs.build_source}} \
        --destination ${{inputs.build_destination}}
    - name: Purge unused CSS
      shell: bash 
      run: |
        npm install -g purgecss
        purgecss -c purgecss.config.js
        echo action done
