name: build_jekyll
description: custom build jekyll
inputs:
  build_source:
    description: source directory for build
    required: true 
    type: string
  build_destination:
    description: destination directory for build
    required: true 
    type: string
  build_script_code:
    description: code for the script that builds the app
    required: true 
    type: string   
  ruby_version: 
    description: python version
    required: true  
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup Ruby     
      uses: ruby/setup-ruby@v1
      with:
        ruby-version:  "${{inputs.ruby_version}}"
        bundler-cache: true 
    - name: build jekyll
      if: "${{contains(inputs.build_script_code,'jekyll')}}"
      shell: bash
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build \
        --source "./${{inputs.build_source}}" \
        --destination "${{inputs.build_destination}}"
    - name: Purge unused CSS
      shell: bash 
      run: |
        npm install -g purgecss
        purgecss -c purgecss.config.js
        echo action done
