name: build_ruby
description: custom build ruby 
runs:
  using: "composite"
  steps:
#    - name: Setup Ruby     
#      uses: ruby/setup-ruby@v1
#      with:
#        ruby-version:  ${{inputs.ruby_version}}
#        bundler-cache: true 
    - name: build jekyll
      if: ${{contains(env.BUILD_TYPE,'ruby-jekyll')}}
      shell: bash
      run: |
        export JEKYLL_ENV=production
        bundle exec jekyll build \
        --source ./${{env.BUILD_ROOT_DIR}} \
        --destination ${{env.BUILD_DESTINATION_DIR}}
