name: build_python
description: custom build python
inputs:
  build_source:
    description: source directory for build
    required: true 
    type: string
  build_destination:
    description: destination directory for build
    required: true 
    type: string
  build_script_code:
    description: code for the script that builds the app
    required: true 
    type: string   
  python_version: 
    description: python version
    required: true 
    type: string
runs:
  using: composite
  steps:
    - name: Setup Python  
      uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python_version}}
        cache: pip # caching pip dependencies
    - name: build jupyterlite-pyodide
      if: ${{contains(inputs.build_script_code,'jupyterlite-pyodide')}}
      shell: bash
      run: |
          pip3 install -r requirements.txt
          jupyter lite build --contents content --output-dir ${{inputs.build_destination}}
    - name: build jupyterlite-xeus
      if: ${{contains(inputs.build_script_code,'jupyterlite-xeus')}}
      uses: mamba-org/setup-micromamba@v1
      with:
          micromamba-version: '1.5.8-0'
          environment-file: environment.yml
          cache-environment: true 
          
