name: build_python
description: custom build python
runs:
  using: composite
  steps:
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: ${{env.PYTHON_VERSION}}
      #  cache: pip # caching gives errors during dev, use only after workflow works
    - name: install python packages using requirements.txt
      if: ${{contains(env.BUILD_TYPE,'install-requirements')}}
      shell: bash    
      run: pip install -r requirements.txt
    - name: install jupyterlite-xeus packages
      if: ${{contains(env.BUILD_TYPE,'mamba')}}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: "${{env.BUILD_ROOT_DIR}}/${{env.MAMBA_ENV_FILE}}"
#  caching gives errors during dev, use only after workflow works        
        cache-environment: true 
    - name: install jupyterlite-xeus packages
      if: ${{contains(env.BUILD_TYPE,'jupyterlite-xeus')}}
      shell: bash -l {0}
      run: |
        jupyter lite build \
        --config ${{env.BUILD_ROOT_DIR}}/jupyter_lite_config.json --output-dir ${{env.BUILD_DESTINATION_DIR}} \
        --lite-dir ${{env.BUILD_ROOT_DIR}} --no-sourcemaps --no-unused-shared-packages \
        --XeusAddon.environment_file=${{env.JPTLITE_XEUS_ENV_FILE}} \
        --XeusAddon.mount_jupyterlite_content=True 
    - name: install jupyterlite-pyodide packages
      if: ${{contains(env.BUILD_TYPE,'jupyterlite-pyodide')}}
      shell: bash -l {0}
      run: | 
        jupyter lite build --base-url ${{env.ACCESS_BASE_PATH}} --output-dir ${{env.BUILD_DESTINATION_DIR}} \
        --config ${{env.BUILD_ROOT_DIR}}/jupyter_lite_config.json --lite-dir ${{env.BUILD_ROOT_DIR}} --no-sourcemaps --no-unused-shared-packages
