name: build_python
description: custom build python
inputs:
  build_source:
    description: source directory for build
    required: true 
    type: string
  build_destination:
    description: destination directory for build
    required: true 
    type: string
  build_script_code:
    description: code for the script that builds the app
    required: true 
    type: string   
  python_version: 
    description: python version
    required: true 
    type: string
  mamba_env_file:
    description: micromamba evironment config file
    required: true 
    type: string   
runs:
  using: composite
  steps:
    - name: Setup Python 
      uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.python_version}}
      #  cache: pip # caching gives errors during dev, use only after workflow works
    - name: install jupyterlite-xeus packages
      if: ${{contains(inputs.build_script_code,'mamba')}}
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: ${{inputs.mamba_env_file}}
        cache-environment: true #  caching gives errors during dev, use only after workflow works
    - name: install jupyterlite-xeus packages
      if: ${{contains(inputs.build_script_code,'jupyterlite-xeus')}}
      shell: bash -l {0}
      run: |
          pip install jupyterlite-xeus
          jupyter lite build \
          --contents content \
          --output-dir ${{inputs.build_destination}} \
          --XeusAddon.mount_jupyterlite_content=True \
    - name: install jupyterlite-pyodide packages
      if: ${{contains(inputs.build_script_code,'jupyterlite-pyodide')}}
      shell: bash
      run: |
          pip install -r requirements.txt        
          jupyter lite build --contents content --output-dir ${{inputs.build_destination}}     
          
