name: build_node
description: custom build node 
runs:
  using: composite
  steps:
  #  - name: Install npm from package-lock.json
  #    uses: bahmutov/npm-install@v1
    - name: Build node project
      shell: bash
      run: |
        npm install
        npm run build
