name: build_node
description: custom build python
runs:
  using: composite
  steps:
    - name: Setup Python 
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
    - name: install and build
      run: cd ${{vars.BUILD_ROOT_DIR}} && npm ${{vars.NPM_INSTALL_COMMAND}}  && npm run ${{vars.NPM_BUILD_COMMAND}} && npm run ${{vars.NPM_PURGECSS_COMMAND}}   
