name: build
on:
  workflow_call       
jobs:   
  build:
    environment: ${{vars.active_repo_env}}
    env:
      GHWFL_BUILD_DESTINATION_DIR: ${{vars.BUILD_DESTINATION_DIR}}
      GHWFL_BUILD_SOURCE_PATH: ${{vars.BUILD_SOURCE_PATH}}
      GHWFL_DEPLOY_HOST_TYPE: ${{vars.DEPLOY_HOST_TYPE}}
      GHWFL_ACCESS_BASE_PATH: ${{vars.ACCESS_BASE_PATH}}
    permissions:
      contents: read
      pages: read
    runs-on: ubuntu-latest
    steps:
      - name: test var and environment
        run: |
          echo ${{vars.APP_NAME}}
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: node install and Build 
        if: ${{contains(vars.BUILD_TYPE,'node')}}     
        run: cd ${{vars.BUILD_ROOT_DIR}} && npm ${{vars.NPM_INSTALL_COMMAND}}  && npm run ${{vars.NPM_BUILD_COMMAND}} && npm run ${{vars.NPM_PURGECSS_COMMAND}}   
      - name: upload artifact for download to deploy outside github
        uses: actions/upload-artifact@v4
        with:
          name: ${{vars.BUILD_ARTIFACT}}
          path: ${{vars.BUILD_DESTINATION_DIR}}
      - name: Upload gh-pages artifact for github pages deploy
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{vars.BUILD_DESTINATION_DIR}} 
  deploy_gh_pages:
    if: ${{vars.DEPLOY_HOST_TYPE}}=='gh_pages'
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4          
          
