name: build
on:
  workflow_call 
# permissions:
#  actions: read 
# env:
#  artifact_name: 'my-artifact'       
jobs:   
  job1:
    environment: ${{vars.active_repo_env}}
    runs-on: ubuntu-latest
    steps:
      - name: test var and environment
        run: |
          echo ${{vars.aws_region}}
      - name: test secret
        if: ${{contains(secrets.user_id=='xmile4ever')}}
        run: |
          echo 'success'
          echo ${{secrets.user_id}}
