name: build and deploy gh-pages
on:
  workflow_call       
jobs:   
  build-python:
    environment: ${{vars.active_repo_env}}
    # the env below is used in vite and prugecss config
    env:
      GHWFL_BUILD_DESTINATION_DIR: ${{vars.BUILD_DESTINATION_DIR}}
      GHWFL_BUILD_SOURCE_PATH: ${{vars.BUILD_SOURCE_PATH}}
      GHWFL_DEPLOY_HOST_TYPE: ${{vars.DEPLOY_HOST_TYPE}}
      GHWFL_ACCESS_BASE_PATH: ${{vars.ACCESS_BASE_PATH}}
    permissions:
      contents: read
      pages: read
    runs-on: ubuntu-latest
    steps:
      - name: install python packages using requirements.txt
        if: ${{contains(vars.BUILD_TYPE,'pip_install_requirements')}}  
        run: pip install -r requirements.txt
      - name: test var and environment
        run: |
          echo ${{env}}
          echo ${{vars}}
          echo
