# A custom workflow for build and deploy.
name: build_deploy_custom
on:
  workflow_call:
    inputs:
      build_source:
        description: source directory for build
        required: false 
        type: string
        default: ./
      build_destination:
        description: destination directory for build
        required: false 
        type: string
        default: _site
      build_languages:
        description: languages used to build code
        required: false 
        type: string
        default: ''
      build_script_code:
        description: code for the script that builds the app
        required: true   
        type: string   
      ruby_version: 
        description: python version
        required: false 
        type: string
        default: 3.3.6
      python_version: 
        description: python version
        required: false 
        type: string
        default: 3.x 
      mamba_env_file: 
        description: micromamba evironment config file
        required: false 
        type: string
        default: environment.yml
      purgecss: 
        description: purgecss
        required: false 
        type: string
        default: 'yes' # yes or no
      deploy_to:
        description: site host type
        required: false 
        type: string
        default: 'gh-pages'
jobs:
  build:
    permissions:
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: checkout file
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: node install and Build 
        if: ${{contains(inputs.build_languages,'node')}}     
        uses: workflows-and-actions/library/.github/actions/build_node@main
      - name: python install and Build 
        if: ${{contains(inputs.build_languages,'python')}}     
        uses: workflows-and-actions/library/.github/actions/build_python@main
        with:
          build_source: ${{inputs.build_source}}
          build_destination: ${{inputs.build_destination}}
          build_script_code: ${{inputs.build_script_code}}
          python_version: ${{inputs.python_version}}
          mamba_env_file: ${{inputs.mamba_env_file}}
      - name: ruby install and Build 
        if: ${{contains(inputs.build_languages,'ruby')}}     
        uses: workflows-and-actions/library/.github/actions/build_ruby@main
        with:
          build_source: ${{inputs.build_source}}
          build_destination: ${{inputs.build_destination}}
          build_script_code: ${{inputs.build_script_code}}
          ruby_version: ${{inputs.ruby_version}}
      - name: jekyll-build-pages@v1
        if: ${{contains(inputs.build_script_code,'gh-pages')}}
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{inputs.build_source}}
          destination: ${{inputs.build_destination}}
      - name: Purge unused CSS
        if: ${{inputs.purgecss=='yes'}} 
        # IMPORTANT: make sure the paths in purgecss config file are consistent with build_destination
        run: |
          ls -R ${{inputs.build_destination}}
          cd ${{inputs.build_destination}}
          purgecss --config ./purgecss.config.js
      #  npm run purge-css --build_destination=${{inputs.build_destination}}
      - name: upload artifact for download from another workflow
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{inputs.build_destination}}
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{inputs.build_destination}}
  deploy_gh_pages:
    if: ${{inputs.deploy_to}}=='gh-pages'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
