name: build
on:
  workflow_call 
# permissions:
#  actions: read 
# env:
#  artifact_name: 'my-artifact'       
jobs:   
  build:
    environment: ${{vars.active_repo_env}}
    env:
      GHWFL_BUILD_DESTINATION_DIR: ${{vars.BUILD_DESTINATION_DIR}}
      GHWFL_BUILD_SOURCE_PATH: ${{vars.BUILD_SOURCE_PATH}}
      GHWFL_DEPLOY_HOST_TYPE: ${{vars.DEPLOY_HOST_TYPE}}
      GHWFL_ACCESS_BASE_PATH: ${{vars.ACCESS_BASE_PATH}}
    permissions:
      contents: read
      pages: write
    runs-on: ubuntu-latest
    steps:
      - name: test var and environment
        run: |
          echo ${{vars.APP_NAME}
      - name: checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: node install and Build 
        if: ${{contains(vars.BUILD_TYPE,'node')}}     
        run: npm run ${{vars.NPM_INSTALL_COMMAND}}  && npm run ${{vars.NPM_BUILD_COMMAND}} && npm run ${{vars.NPM_PURGECSS_COMMAND}}   
