name: build
on:
  workflow_call 
# permissions:
#  actions: read 
# env:
#  artifact_name: 'my-artifact'       
jobs:   
  job1:
    environment: ${{vars.active_repo_env}}
    runs-on: ubuntu-latest
    permissions:
    # needed by aws-actions/configure-aws-credentials
      contents: read
      id-token: write
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_GITHUB_DEPLOYER }} 
          role-session-name: aws-github-hookup
          aws-region: ${{vars.aws_region}}
      - name: test var and environment
        run: |
          echo ${{vars.aws_region}}
          echo ${{secrets.user_id=='xmile4ever'}}
