# A custom workflow for build and deploy.
name: build_deploy_custom
on:
  workflow_call:
    inputs:
      build_source:
        description: source directory for build
        required: false 
        type: string
        default: ./
      build_destination:
        description: destination directory for build
        required: false 
        type: string
        default: _site
      sparse_checkout:
        description: action/checkout only selected directory
        required: false 
        type: string
        default: true 
      build_languages:
        description: languages used to build code
        required: false 
        type: string
        default: ''
      build_script_code:
        description: code for the script that builds the app
        required: false  
        type: string   
        default: 'gh-pages'
      ruby_version: 
        description: python version
        required: false 
        type: string
        default: 3.3.x
      python_version: 
        description: python version
        required: false 
        type: string
        default: 3.x
      deploy_to:
        description: site host type
        required: false 
        type: string
        default: 'gh-pages'
jobs:
  build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: checkout file
        uses: actions/checkout@v4
        if: inputs.sparse_checkout
        with:
          sparse-checkout: |
            ${{inputs.build_source}}
        # cone mode false means will checkout only the file/files mentioned in the path
        # default is true which checks out repository root level files unnecessarily for our case
          sparse-checkout-cone-mode: false  
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: install and Build 
        if: ${{contains(inputs.build_languages,'python')}}     
        uses: workflows-and-actions/library/.github/actions/build_python@main
        with:
          build_source: ${{inputs.build_source}}
          build_destination: ${{inputs.build_destination}}
          build_script_code: ${{inputs.build_script_code}}
          python_version: ${{inputs.python_version}}
      - name: ruby install and Build 
        if: ${{contains(inputs.build_languages,'ruby')}}     
        uses: workflows-and-actions/library/.github/actions/build_ruby@main
        with:
          build_source: ${{inputs.build_source}}
          build_destination: ${{inputs.build_destination}}
          build_script_code: ${{inputs.build_script_code}}
          ruby_version: ${{inputs.ruby_version}}
      - name: jekyll-build-pages@v1
        if: ${{contains(inputs.build_script_code,'gh-pages')}}
        uses: actions/jekyll-build-pages@v1
        with:
          source: ${{inputs.build_source}}
          destination: ${{inputs.build_destination}}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{inputs.build_destination}}
  deploy_gh_pages:
    if: ${{inputs.deploy_to}}=='gh-pages'
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
